#
# Webcampak Docs - Config
#
site_name: Webcampak Docs
site_url: http://doc.webcampak.com
repo_url: https://github.com/Webcampak/Documentation
copyright: "&copy; 2015-2016"
theme_dir: theme
pages:
- Home: 'index.md'
- Learn:
  - Overview: 'Learn/en_Overview.md'
  - Sources: 'Learn/en_Sources.md'
  - Capture: 'Learn/en_Capture.md'
  - Logging: 'Learn/en_Logging.md'
  - File Management: 'Learn/en_File_Management.md'
  - Users: 'Learn/en_Users.md'
- Use:
  - Overview: 'Learn/en_Overview.md'
- Configure:
  - Sources: 'Configure/en_Sources.md'
  - Access Control: 'Configure/en_Access_Control.md'
- Develop:
  - Installation: 'Develop/en_Install.md'
  - Initial Setup: 'Develop/en_Initial_Setup.md'
extra:
  project_root_dir: '/webcampak3.x/web/en/'
  project_org: 'Webcampak'
  project_description: 'Webcampak Docs'
  version: 1.0
markdown_extensions:
  - BSCodeTabExtension:
      default_lang: 'Source'
      show_all_code_as_folders: True
      animate_tab_transitions: False
